mybatis-plus:
  configuration:
#    #    mybatis-plus 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  mapper-locations: classpath:mapper/*.xml


spring:
  datasource:
    # 这里使用了第三方插件 用于sql效率分析不使用这个插件的话用下面的url和driver-class-name
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:p6spy:mysql://localhost:3306/flash_sales_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://localhost:3306/flash_sales_system
#    url: jdbc:p6spy:mysql://localhost:3306/mybatis-plus
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  profiles:
    active: dev

